
import { AppConfig } from './types';

export const appConfig: AppConfig = {
    app: {
        name: "SkinCheck AI",
        description: "Dermatologue virtuel professionnel",
        theme: {
            primaryColor: "#059669", // Emerald-600 (Darker green for buttons)
            background: "#F9FAFB", // Gray-50
            card: "#FFFFFF",
            accent: "#D1FAE5", // Emerald-100
            radius: 20, // Example radius
            font: "Inter, sans-serif",
        },
        layout: {
            header: {
                logoText: "DERMO-CHECK",
                subtitle: "Votre dermatologue virtuel de confiance",
                nav: [
                    { id: "questionnaire", label: "Auto analyse" },
                    { id: "find-dermatologist", label: "Trouver un dermato" },
                    { id: "dictionary", label: "Dictionnaire" },
                    { id: "blog", label: "Revue" },
                    { id: "about", label: "À propos" },
                    { id: "contact", label: "Contact" },
                ],
            },
            hero: {
                title: "Analyse dermatologique intelligente",
                subtitle: "Obtenez une évaluation de vos problèmes de peau en quelques minutes.",
                cta: { label: "Commencer la consultation", target: "questionnaire" },
                illustration: { type: "DermoCheckLogo", prompt: "none" }, // Changed to use DermoCheckLogo type
                badges: ["Analyse rapide", "Confidentiel", "Anonyme"],
            },
        },
        pages: [
            {
                id: "home",
                title: "Bienvenue sur DERMO-CHECK AI",
                description: "Votre assistant dermatologique personnel.",
                sections: [
                    // Removed the 'cards' section as it is now handled by FeaturesSection component
                    {
                        type: "banner",
                        style: "warning",
                        text: "Avertissement : Cette application est à titre informatif et ne remplace pas une consultation médicale. En cas d'urgence, consultez un professionnel de santé.",
                    },
                ],
            },
            {
                id: "questionnaire",
                title: "Votre Consultation AI",
                steps: [], // Steps are dynamically generated by Gemini
            },
            {
                id: "about",
                title: "À PROPOS DE DERMO-CHECK AI : L'INNOVATION AU SERVICE DE VOTRE PEAU",
                sections: [
                    {
                        type: "text",
                        title: "NOTRE MISSION ET NOTRE VISION",
                        text: "DERMO-CHECK AI a été conçu avec une mission claire : rendre l'expertise dermatologique de premier niveau accessible, rapide et anonyme à tous. Inspiré par plus de deux décennies d'expérience clinique, notre objectif est de démystifier les préoccupations cutanées en vous offrant une première compréhension éclairée de votre situation, directement depuis chez vous.",
                    },
                    {
                        type: "text",
                        title: "L'APPROCHE DERMO-CHECK AI : UNE EXPERTISE CLINIQUEMENT INSPIRÉE",
                        text: "Notre intelligence artificielle reproduit la démarche d'un dermatologue expérimenté. À travers un dialogue structuré, DERMO-CHECK AI vous guide pas à pas, posant des questions ciblées sur l'historique de vos lésions, vos symptômes, vos antécédents et votre environnement. L'analyse de vos réponses, complétée par l'examen des photos que vous téléchargez (si applicable), permet de générer un rapport préliminaire professionnel. Ce rapport inclut une synthèse clinique, des hypothèses dermatologiques nuancées et des recommandations pratiques.",
                    },
                    {
                        type: "text",
                        title: "TECHNOLOGIE ET SÉCURITÉ : L'INTELLIGENCE ARTIFICIELLE AU CŒUR DE NOS VALEURS",
                        text: "DERMO-CHECK AI s'appuie sur des modèles d'IA avancés pour analyser les données que vous fournissez. La confidentialité est notre priorité absolue : toutes les informations partagées sont traitées de manière anonyme, sont chiffrées et ne sont jamais stockées durablement. Elles sont utilisées uniquement pour générer votre rapport et sont supprimées automatiquement après chaque consultation. Vous bénéficiez ainsi d'une analyse rigoureuse en toute sécurité et sans compromis sur votre vie privée.",
                    },
                    {
                        type: "warning",
                        text: "AVERTISSEMENT CRUCIAL : DERMO-CHECK AI est un outil d'aide à l'orientation et ne peut en aucun cas remplacer une consultation médicale professionnelle, un diagnostic établi par un médecin qualifié, ou un plan de traitement personnalisé. Un examen clinique en personne est indispensable pour confirmer toute hypothèse et assurer une prise en charge adéquate. En cas d'urgence, de douleur intense, de fièvre, de lésion qui s'étend ou change rapidement, ou de localisation sensible (zones intimes, visage), veuillez consulter immédiatement un professionnel de santé.",
                    },
                ],
            },
            {
                id: "blog",
                title: "BLOG & ACTUALITÉS DERMATOLOGIQUES",
                description: "Restez informé sur la santé de la peau, les dernières recherches et les conseils de prévention.",
                sections: [
                    {
                        type: "articles",
                        items: [
                            {
                                title: "Les bienfaits de la vitamine C pour votre peau",
                                excerpt: "Découvrez comment la vitamine C peut transformer votre routine de soins.",
                                tag: "Antioxydants",
                                date: "12 mars 2025",
                            },
                            {
                                title: "Comprendre l'eczéma : causes, symptômes et traitements",
                                excerpt: "Un guide complet pour gérer cette condition cutanée courante.",
                                tag: "Conditions cutanées",
                                date: "28 février 2025",
                            },
                            {
                                title: "Protection solaire : au-delà de l'été",
                                excerpt: "Pourquoi la protection solaire est essentielle toute l'année.",
                                tag: "Prévention",
                                date: "15 janvier 2025",
                            },
                        ],
                    },
                ],
                autoUpdate: {
                    everyDays: 7,
                    placeholderArticle: {
                        title: "Les mystères de l'hydratation cutanée",
                        excerpt: "Explorez les secrets d'une peau souple et hydratée.",
                        tag: "Hydratation"
                    }
                }
            },
            {
                id: "dictionary",
                title: "DICTIONNAIRE DERMATOLOGIQUE",
                description: "Trouvez des définitions claires pour les termes médicaux liés à la peau et à la cosmétologie.",
                sections: [
                    {
                        type: "dictionary",
                        dictionaryTerms: [
                            { term: "Acide Hyaluronique", definition: "Molécule naturellement présente dans la peau, essentielle à l'hydratation et à l'élasticité. Utilisée en cosmétique et en médecine esthétique pour repulper et hydrater." },
                            { term: "Acné", definition: "Maladie inflammatoire chronique du follicule pilosébacé, caractérisée par des comédons, papules, pustules et kystes." },
                            { term: "Acné Kystique", definition: "Forme sévère d'acné caractérisée par de gros kystes inflammatoires profonds, souvent douloureux, pouvant laisser des cicatrices importantes." },
                            { term: "Allergie", definition: "Réaction anormale du système immunitaire à une substance étrangère (allergène)." },
                            { term: "Anti-âge", definition: "Produits ou traitements visant à prévenir ou corriger les signes du vieillissement cutané, tels que les rides, ridules et la perte de fermeté." },
                            { term: "Atopie", definition: "Prédisposition génétique à développer des allergies, souvent associée à l'eczéma, l'asthme et la rhinite allergique." },
                            { term: "Biopsie", definition: "Prélèvement d'un fragment de tissu ou d'organe pour un examen microscopique." },
                            { term: "Botox (Toxine Botulique)", definition: "Neurotoxine utilisée en médecine esthétique pour détendre temporairement les muscles faciaux et lisser les rides d'expression." },
                            { term: "Brûlure (cutanée)", definition: "Lésion de la peau causée par la chaleur, des produits chimiques, l'électricité ou le rayonnement. Classée en degrés selon la profondeur des tissus affectés." },
                            { term: "Carcinome", definition: "Cancer développé à partir des cellules épithéliales (peau, muqueuses, glandes)." },
                            { term: "Cellulite (peau d'orange)", definition: "Accumulation de graisse sous la peau, modifiant son aspect et lui donnant un aspect capitonné. Différent de la cellulite infectieuse." },
                            { term: "Chimiothérapie", definition: "Traitement des cancers par des substances chimiques qui détruisent les cellules cancéreuses." },
                            { term: "Cicatrice", definition: "Marque visible qui demeure après la guérison d'une plaie ou d'une lésion." },
                            { term: "Cloque", definition: "Lésion cutanée remplie de liquide, également appelée bulle ou vésicule selon sa taille." },
                            { term: "Collagène", definition: "Protéine structurale majeure du tissu conjonctif, essentielle à l'élasticité et à la fermeté de la peau. Sa production diminue avec l'âge." },
                            { term: "Comédon", definition: "Lésion élémentaire de l'acné, correspondant à un bouchon de sébum et de cellules mortes. Peut être ouvert (point noir) ou fermé (point blanc)." },
                            { term: "Couperose", definition: "Forme de rosacée caractérisée par des rougeurs diffuses et des petits vaisseaux sanguins dilatés (télangiectasies) sur le visage." },
                            { term: "Crème Solaire", definition: "Produit topique conçu pour protéger la peau des rayons ultraviolets (UVA et UVB) du soleil, prévenant les coups de soleil et le photovieillissement." },
                            { term: "Cryothérapie", definition: "Traitement utilisant le froid extrême pour détruire des tissus anormaux, comme les verrues ou certaines lésions pré-cancéreuses." },
                            { term: "Curetage", definition: "Technique chirurgicale consistant à racler une lésion cutanée à l'aide d'une curette." },
                            { term: "Dermabrasion", definition: "Technique de resurfaçage cutané qui utilise un appareil rotatif pour enlever les couches superficielles de la peau, réduisant cicatrices et rides." },
                            { term: "Dermatite", definition: "Inflammation de la peau." },
                            { term: "Dermatoscope", definition: "Instrument optique permettant l'examen détaillé des lésions cutanées, notamment des grains de beauté, pour détecter précocement les cancers cutanés." },
                            { term: "Dermatomycose", definition: "Infection de la peau causée par des champignons (mycoses cutanées)." },
                            { term: "Derme", definition: "Couche de la peau située sous l'épiderme, riche en collagène, élastine et vaisseaux sanguins. Responsable de la souplesse et de la résistance de la peau." },
                            { term: "Détatouage", definition: "Technique utilisant diverses méthodes (laser, chirurgie) pour atténuer ou supprimer un tatouage." },
                            { term: "Diagnostic", definition: "Identification d'une maladie à partir de ses symptômes et des examens complémentaires." },
                            { term: "Dyschromie", definition: "Toute altération de la coloration normale de la peau, incluant hyperpigmentation (taches sombres) ou hypopigmentation (taches claires)." },
                            { term: "Eczéma", definition: "Dermatose inflammatoire caractérisée par des plaques rouges, des vésicules, des croûtes et des démangeaisons intenses." },
                            { term: "Épiderme", definition: "Couche la plus superficielle de la peau, assurant une fonction de barrière protectrice contre les agressions extérieures et la déshydratation." },
                            { term: "Épilation Laser", definition: "Technique d'épilation définitive qui utilise un faisceau laser pour détruire le follicule pileux à la racine." },
                            { term: "Éruption", definition: "Apparition rapide de lésions cutanées (boutons, taches, etc.) sur une zone plus ou moins étendue du corps." },
                            { term: "Érythème", definition: "Rougeur de la peau due à une dilatation des vaisseaux sanguins, s'effaçant à la pression." },
                            { term: "Exérèse", definition: "Ablation chirurgicale d'une lésion ou d'une tumeur." },
                            { term: "Fissure", definition: "Gerçure linéaire profonde de la peau, souvent douloureuse, apparaissant sur des zones de flexion ou de sécheresse intense." },
                            { term: "Folliculite", definition: "Inflammation d'un ou plusieurs follicules pileux, se manifestant par des petits boutons rouges ou pustules centrés sur un poil." },
                            { term: "Glande Sébacée", definition: "Glande cutanée qui produit le sébum, une substance grasse qui lubrifie et protège la peau et les cheveux." },
                            { term: "Gommage", definition: "Produit ou technique d'exfoliation douce qui élimine les cellules mortes de la surface de la peau, favorisant le renouvellement cellulaire et l'éclat." },
                            { term: "Grain de beauté", definition: "Lésion pigmentée bénigne de la peau, également appelée nævus. Son aspect doit être surveillé pour détecter tout changement suspect." },
                            { term: "Herpès", definition: "Infection virale récurrente se manifestant par des vésicules groupées sur la peau ou les muqueuses, souvent autour de la bouche (bouton de fièvre)." },
                            { term: "Hirsutisme", definition: "Développement excessif de poils terminaux chez la femme dans des zones normalement masculines (lèvre supérieure, menton, poitrine, dos)." },
                            { term: "Histologie", definition: "Étude microscopique des tissus biologiques, souvent réalisée après une biopsie pour établir un diagnostic." },
                            { term: "Hydratation", definition: "Processus par lequel la peau maintient son niveau d'eau. Indispensable à la fonction barrière et à la souplesse de la peau. Les produits hydratants aident à retenir l'eau." },
                            { term: "Hyperkératose", definition: "Épaississement de la couche cornée de l'épiderme, souvent en réponse à une irritation ou une pression chronique." },
                            { term: "Impetigo", definition: "Infection cutanée bactérienne superficielle et très contagieuse, caractérisée par des croûtes jaunâtres. Fréquente chez les enfants." },
                            { term: "Inflammation", definition: "Réaction de défense de l'organisme face à une agression (infection, irritation), se manifestant par rougeur, chaleur, douleur et gonflement." },
                            { term: "Injections Esthétiques", definition: "Procédures médicales non chirurgicales, telles que les injections d'acide hyaluronique ou de toxine botulique, visant à corriger les signes du vieillissement ou à améliorer certains traits du visage." },
                            { term: "Jonction Dermo-épidermique", definition: "Zone de liaison entre l'épiderme et le derme, essentielle pour la cohésion de la peau et le passage des nutriments." },
                            { term: "Kératinocyte", definition: "Cellule majoritaire de l'épiderme, productrice de kératine, qui assure la fonction barrière de la peau." },
                            { term: "Kyste", definition: "Cavité pathologique, généralement remplie de liquide ou de matière semi-solide, développée dans un tissu." },
                            { term: "Laser", definition: "Technologie utilisant un faisceau lumineux concentré pour traiter diverses affections cutanées (épilation, taches pigmentaires, cicatrices, lésions vasculaires)." },
                            { term: "Lentigo", definition: "Tache pigmentée bénigne de la peau, souvent due à l'exposition solaire (lentigo solaire ou sénile)." },
                            { term: "Lésion", definition: "Toute altération ou anomalie visible d'un tissu ou d'un organe." },
                            { term: "Lichen plan", definition: "Maladie inflammatoire chronique de la peau et des muqueuses, caractérisée par des papules violacées prurigineuses." },
                            { term: "Lifting", definition: "Intervention chirurgicale visant à retendre la peau relâchée du visage et du cou pour rajeunir l'apparence." },
                            { term: "Lupus", definition: "Maladie auto-immune qui peut affecter la peau, les articulations et divers organes, avec des manifestations cutanées variées." },
                            { term: "Macule", definition: "Tache cutanée plane, non palpable, de couleur différente de la peau environnante." },
                            { term: "Mélasma", definition: "Hyperpigmentation acquise, souvent symétrique, apparaissant sous forme de taches sombres sur le visage, liée à l'exposition solaire et aux hormones (masque de grossesse)." },
                            { term: "Mélanome", definition: "Tumeur maligne dérivée des mélanocytes, cellules productrices de pigments. C'est le cancer de la peau le plus agressif." },
                            { term: "Microdermabrasion", definition: "Technique d'exfoliation mécanique douce qui utilise de micro-cristaux ou une pointe diamantée pour poncer la couche superficielle de la peau, améliorant le teint et la texture." },
                            { term: "Nævus", definition: "Terme médical pour un grain de beauté." },
                            { term: "Nécrose", definition: "Mort des cellules ou des tissus d'un organisme vivant, généralement due à un manque d'oxygène ou à une lésion." },
                            { term: "Nodule", definition: "Petite formation solide, palpable, généralement sphérique, située dans le derme ou l'hypoderme." },
                            { term: "Œdème", definition: "Gonflement des tissus dû à une accumulation excessive de liquide." },
                            { term: "Ongle incarné", definition: "Affection où l'ongle pénètre dans la chair du doigt ou de l'orteil, provoquant douleur et inflammation." },
                            { term: "Papule", definition: "Petite lésion cutanée solide et palpable, surélevée, de moins de 1 cm de diamètre." },
                            { term: "Pathologie", definition: "Étude des maladies ; désigne également la maladie elle-même." },
                            { term: "Peeling", definition: "Traitement dermatologique ou esthétique qui consiste à appliquer une solution chimique sur la peau pour provoquer une exfoliation contrôlée, améliorant l'aspect et la texture." },
                            { term: "Photothérapie", definition: "Traitement utilisant des longueurs d'onde spécifiques de lumière (UVB, LED) pour traiter diverses affections cutanées comme le psoriasis ou l'eczéma." },
                            { term: "Photovieillissement", definition: "Vieillissement prématuré de la peau causé principalement par l'exposition chronique aux rayons ultraviolets du soleil, se manifestant par rides, taches et perte d'élasticité." },
                            { term: "Pigmentation", definition: "Coloration des tissus due à la présence de pigments comme la mélanine." },
                            { term: "Pores (dilatés)", definition: "Ouvertures des follicules pilosébacés qui apparaissent plus grands que la normale, souvent sur les peaux grasses et mixtes." },
                            { term: "Prurit", definition: "Sensation de démangeaison intense." },
                            { term: "Psoriasis", definition: "Maladie inflammatoire chronique de la peau, caractérisée par des plaques rouges bien délimitées, recouvertes de squames argentées." },
                            { term: "Radiothérapie", definition: "Traitement des cancers utilisant des radiations ionisantes." },
                            { term: "Rétinol (Vitamine A)", definition: "Dérivé de la vitamine A largement utilisé en cosmétique pour ses propriétés anti-âge, anti-acnéiques et régénératrices." },
                            { term: "Rides", definition: "Plis ou sillons permanents de la peau, formés par le vieillissement cutané, la perte de collagène et d'élastine, et les mouvements musculaires répétés." },
                            { term: "Rosacée", definition: "Maladie cutanée chronique du visage caractérisée par des rougeurs, des petits vaisseaux visibles et parfois des boutons. La couperose en est une forme." },
                            { term: "Scabiose", definition: "Infection cutanée contagieuse causée par un acarien (sarcopte) qui creuse des sillons dans l'épiderme, provoquant des démangeaisons intenses." },
                            { term: "Sclérothérapie", definition: "Traitement médical qui consiste à injecter une solution sclérosante dans les varices ou les petites télangiectasies pour les faire disparaître." },
                            { term: "Sébum", definition: "Substance grasse produite par les glandes sébacées, qui lubrifie et protège la peau et les cheveux." },
                            { term: "Soin anti-taches", definition: "Produits ou traitements visant à réduire ou éliminer les taches pigmentaires (mélasma, lentigos) et à unifier le teint." },
                            { term: "Squame", definition: "Lamelle de peau sèche qui se détache de l'épiderme, signe d'une desquamation anormale." },
                            { term: "Télangiectasie", definition: "Dilatation permanente de petits vaisseaux sanguins visibles à la surface de la peau, souvent fines et rouges ou violacées." },
                            { term: "Traitement", definition: "Ensemble des moyens mis en œuvre pour soigner une maladie." },
                            { term: "Ulcère", definition: "Lésion cutanée profonde avec perte de substance, qui ne cicatrise pas spontanément." },
                            { term: "Urticaire", definition: "Éruption cutanée caractérisée par des plaques rouges, en relief (papules érythémateuses), très prurigineuses, semblables à des piqûres d'ortie." },
                            { term: "Vascularite", definition: "Inflammation des vaisseaux sanguins." },
                            { term: "Vergetures", definition: "Lésions cutanées linéaires ressemblant à des cicatrices, résultant d'un étirement excessif et rapide de la peau (grossesse, prise de poids)." },
                            { term: "Verrue", definition: "Petite excroissance cutanée bénigne causée par le virus du papillome humain (VPH)." },
                            { term: "Vésicule", definition: "Petite cloque cutanée de moins de 5 mm, contenant du liquide clair." },
                            { term: "Vitiligo", definition: "Maladie caractérisée par une dépigmentation progressive de la peau sous forme de taches blanches, due à la destruction des mélanocytes." },
                            { term: "Xérose", definition: "Sécheresse cutanée pathologique, caractérisée par une peau rugueuse, squameuse et parfois prurigineuse, due à une altération de la barrière cutanée." },
                            { term: "Zona", definition: "Infection virale due à la réactivation du virus de la varicelle-zona, se manifestant par une éruption douloureuse de vésicules le long d'un dermatome." },
                        ],
                    },
                ],
            },
            {
                id: "contact",
                title: "CONTACTEZ-NOUS",
                description: "Une question, une suggestion ou besoin d'aide ? N'hésitez pas à nous contacter.",
                fields: [
                    { name: "name", label: "Votre Nom", type: "text", required: true },
                    { name: "email", label: "Votre Email", type: "email", required: true },
                    { name: "subject", label: "Sujet", type: "text", required: true },
                    { name: "message", label: "Votre Message", type: "textarea", required: true },
                ],
            },
            {
                id: "faq",
                title: "QUESTIONS FRÉQUENTES (FAQ)",
                sections: [
                    {
                        type: "text",
                        title: "Qu'est-ce que DERMO-CHECK AI ?",
                        text: "DERMO-CHECK AI est un outil d'assistance dermatologique basé sur l'intelligence artificielle. Il vous pose des questions structurées et analyse les informations fournies, y compris les photos, pour générer un rapport préliminaire sur votre condition cutanée. **Il ne remplace pas une consultation médicale.**",
                    },
                    {
                        type: "text",
                        title: "Comment fonctionne la consultation AI ?",
                        text: "Vous interagissez avec notre IA en répondant à une série de questions sur vos symptômes, l'historique de la lésion, vos antécédents, etc. Vous pouvez également télécharger une ou plusieurs photos de la lésion. L'IA utilise ces informations pour formuler des hypothèses et des conseils.",
                    },
                    {
                        type: "text",
                        title: "Mes données sont-elles sécurisées ?",
                        text: "Absolument. Toutes les données que vous fournissez sont traitées de manière anonyme et ne sont pas conservées après la consultation. Nous n'utilisons aucune information pour vous identifier ou à des fins autres que l'analyse de votre demande ponctuelle. **Votre vie privée est notre priorité.**",
                    },
                    {
                        type: "text",
                        title: "Puis-je utiliser cette application pour un diagnostic ?",
                        text: "**Non, DERMO-CHECK AI ne fournit pas de diagnostic médical.** Les informations et hypothèses générées sont à titre indicatif et ne remplacent en aucun cas l'avis, le diagnostic ou le traitement d'un professionnel de santé qualifié. Consultez toujours un dermatologue pour un diagnostic précis.",
                    },
                ],
            },
            {
                id: "privacy-policy",
                title: "POLITIQUE DE CONFIDENTIALITÉ",
                sections: [
                    {
                        type: "text",
                        title: "Collecte et Utilisation des Données",
                        text: "Nous nous engageons à protéger votre vie privée. DERMO-CHECK AI ne collecte, ne stocke ni ne partage aucune information personnelle identifiable. Toutes les données que vous saisissez ou téléchargez sont utilisées uniquement pour la durée de votre consultation, puis sont supprimées de nos systèmes. **Aucune donnée n'est conservée à long terme.**",
                    },
                    {
                        type: "text",
                        title: "Sécurité des Données",
                        text: "Nous mettons en œuvre des mesures de sécurité robustes pour protéger l'intégrité et la confidentialité de vos informations pendant la consultation. Le trafic entre votre appareil et nos serveurs est chiffré. Cependant, aucune méthode de transmission sur Internet ou de stockage électronique n'est totalement sécurisée.",
                    },
                    {
                        type: "text",
                        title: "Consentement",
                        text: "En utilisant DERMO-CHECK AI, vous consentez à notre politique de confidentialité décrite ci-dessus. Si vous n'acceptez pas ces termes, veuillez ne pas utiliser notre application.",
                    },
                ],
            },
            {
                id: "terms-of-use",
                title: "CONDITIONS D’UTILISATION",
                sections: [
                    {
                        type: "text",
                        title: "Acceptation des Conditions",
                        text: "En accédant et en utilisant DERMO-CHECK AI, vous acceptez d'être lié par les présentes Conditions d'Utilisation. Si vous n'acceptez pas toutes les conditions, vous n'êtes pas autorisé à utiliser l'application.",
                    },
                    {
                        type: "text",
                        title: "Nature du Service",
                        text: "DERMO-CHECK AI fournit un outil d'information et d'orientation. **Il n'est pas un substitut à un avis médical professionnel, un diagnostic ou un traitement.** Cherchez toujours l'avis de votre médecin ou d'un autre professionnel de la santé qualifié pour toute question concernant une condition médicale.",
                    },
                    {
                        type: "text",
                        title: "Limitation de Responsabilité",
                        text: "DERMO-CHECK AI ne peut être tenu responsable des dommages directs ou indirects résultant de l'utilisation ou de l'incapacité d'utiliser le service, y compris, sans s'y limiter, la perte de données ou de bénéfices. L'utilisation de l'application est à vos propres risques.",
                    },
                    {
                        type: "text",
                        title: "Modifications des Conditions",
                        text: "Nous nous réservons le droit de modifier ces Conditions d'Utilisation à tout moment. Toute modification sera effective dès sa publication sur cette page. Il est de votre responsabilité de consulter régulièrement ces conditions.",
                    },
                ],
            },
            {
                id: "find-dermatologist",
                title: "TROUVER UN DERMATOLOGUE",
                description: "Utilisez notre outil pour localiser des dermatologues près de chez vous grâce à Google Maps. Un professionnel de santé est indispensable pour un diagnostic.",
            },
        ],
        uiGuidelines: {
            cardsRounded: true,
            shadows: "lg",
            showProgressOnQuestionnaire: true,
            useMedicalIcons: true,
            tone: "professional_reassuring",
            showDisclaimerAtTop: true,
        },
    },
};
